# Lab 16 - Numpy

### 1. Create a 1D array with elements from 1 to 10.

In [22]:
# Importing important libraries
import numpy as np

# Creating an array
arr = np.arange(1,11)
# Printing the array
print(f'Array : {arr}')

Array : [ 1  2  3  4  5  6  7  8  9 10]


### 2. Create a 2D array of size 3x3 filled with zeros.

In [3]:
# Importing important libraries
import numpy as np

# Creating an 2D array of zeros
arr = np.zeros((3,3),int)
# Printing the array
print(f'Array : \n{arr}')

Array : 
[[0 0 0]
 [0 0 0]
 [0 0 0]]


### 3. Find the maximum and minimum values in an array.

In [11]:
# Importing important libraries
import numpy as np

# Creating the function
def min_max(arr):
    # Returning the minimum and maximum of the array
    return print(f'Minimum : {np.min(arr)} \nMaximum : {np.max(arr)}')

# Taking input from user and calling function
min_max(eval(input('Enter an array :')))

Enter an array : [[2,4,5],[1,0,3]]


Minimum : 0 
Maximum : 5


### 4. Reshape a 1D array into a 2D array of shape 2x5.

In [33]:
# Importing important libraries
import numpy as np

# Creating function
def arr_reshape(arr,row,col):
    # Cade where error can occur
    try:
        # Reshaping the array from 1D to 2D
        new_arr = np.reshape(arr,(row,col))

    # Catching the error and printing error message
    except ValueError:
        return print(f'Error : Row & Columns should give {len(arr)} when multiplied.')
    # Execting the program if there's no error
    else:
        return print(f'The 2D array is : \n{new_arr}')

# Taking input from user and calling functions
arr_reshape(eval(input('Enter an array :')),int(input('Enter the Row size :')),int(input('Enter the Column size :')))

Enter an array : [1,2,3,4,5,6,7,8,9,0]
Enter the Row size : 5
Enter the Column size : 2


The 2D array is : 
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


### 5. Generate a 1D array of 5 random integers between 10 and 50.

In [7]:
# Importing important libraries
import numpy as np

# Creating function
def rand_num(start, end, count):
    # Generating array of random numbers
    arr = np.random.randint(start,end,count)
    # Returning the output
    return print(f'{count} random numbers between {start} & {end} are : {arr}')

# Taking input from user and calling fnuctions
rand_num(int(input('Enter the Starting number :')),int(input('Enter the Ending number :')),int(input('Enter the Count :')))

Enter the Starting number : 10
Enter the Ending number : 50
Enter the Count : 10


10 random numbers between 10 & 50 are : [16 18 27 35 17 25 44 46 47 31]


### 6. Convert the below list into numpy array then display the array
- Input: my_list = [1, 2, 3, 4, 5]

In [13]:
# Importing important libraries
import numpy as np

# Calling function
def list_to_array(lst):
    # Creating array from list
    arr = np.array(lst)
    # Returning the output
    return print(f'List : {lst} \nArray : {arr}')

# Taking input from the user and calling the function
list_to_array(eval(input('Enter a list to convert into array :')))

Enter a list to convert into array : [2,3,4,5,6]


List : [2, 3, 4, 5, 6] 
Array : [2 3 4 5 6]


### 7. Convert the below list into a numpy array then display the array then display the first and last index and then multiply each element by 2 and display the result.
- Input: my_list = [1, 2, 3, 4, 5]

In [11]:
# Importing important libraries
import numpy as np

# Creating function
def list_detail(lst):
    # Converting list into array
    arr = np.array(lst)
    # Printing array, first index and last index
    print(f'Array : {arr}')
    print(f'First Index : {arr[0]}')
    print(f'Last Index  : {arr[-1]}')
    # Printing the array after multipling it by 2
    print(f'Multiplied by 2 : {arr*2}')

# Taking input from user and Calling function
list_detail(eval('Enter the list to convert into array and get details : '))

Array : [1 2 3 4 5]
First Index : 1
Last Index  : 5
Multiplied by 2 : [ 2  4  6  8 10]
